### ISSUE TITLE
fallback language problems

### ISSUE THREAD

**Issue by tautomer** [Magisk-Modules-Repo/Magisk-ios10-Emoji-font#3] opened 2017-04-03 15:21 UTC
Running on OnePlus 3, oxygen os 4.1.1

All Chinese characters became squares after installation. 

I managed to locate the problem in fallback_fonts.xml.
><family>
        <fileset>
            <file lang="zh-Hans">NotoSansSC-Regular.otf</file>
        </fileset>
    </family>
    <family>
        <fileset>
            <file lang="zh-Hant">NotoSansTC-Regular.otf</file>
        </fileset>
    </family>
    <family>
        <fileset>
            <file lang="ja">NotoSansJP-Regular.otf</file>
        </fileset>
    </family>
    <family>
        <fileset>
            <file lang="ko">NotoSansKR-Regular.otf</file>
        </fileset>
    </family><

Those files do not exist in my ROM, but there is the all-in-one font 'NotoSansCJK-Regular.ttc', instead. After replacing those names with 'NotoSansCJK-Regular.ttc', CJK can be shown correctly. However, some other languages are still shown in squares. Here is a screenshot.

![image](https://cloud.githubusercontent.com/assets/15900605/24616533/6b42c52c-185f-11e7-8bd8-9e6c62d7d504.png)

I am not familiar with these languages and not using them at all, either, but is might be a problem to the other users.

**Comment by jplwolters** [comment] 2017-04-04 06:40
I know what the problem is. I will try to fix this issue in the next week.

**Comment by jplwolters** [comment] 2017-04-12 12:32
It is fixed in version 5 :)

**Closed by jplwolters** 2017-04-12 12:32 UTC

**Comment by tautomer** [comment] 2017-04-12 13:41
tested and worked.

thx.
