### ISSUE TITLE
Chinese,Japanese, Korean characters do not display correctly 

### ISSUE THREAD

**Issue by cheatmo** [Magisk-Modules-Repo/Magisk-ios10-Emoji-font#4] opened 2017-04-04 05:38 UTC
Hi, I am using HTC10 with venom 5.80 rom
With magisk 12.
After install emoji font, my phone cannot display Chinese, Japanese, Korean...  correctly, after disable all work fine.
Can I do something to fix this? 
Thanks so much!

**Comment by jplwolters** [comment] 2017-04-04 06:41
I know what the problem is. Will fix this in the next week. Thx for you feedback

**Comment by jplwolters** [comment] 2017-04-12 12:32
It is fixed in version 5 :)

**Closed by jplwolters** 2017-04-12 12:32 UTC

**Comment by cheatmo** [comment] 2017-04-14 08:49
Thanks :)
